import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { ConvexClientProvider } from "@/components/provider/ConvexClientProvider";
import { ConvexAuthNextjsServerProvider } from "@convex-dev/auth/nextjs/server";
import Modals from "@/components/provider/Modals";
import NetworkStatus from "@/components/provider/NetworkStatus";
import { ThemeProvider } from "@/components/provider/theme-provider";
import ToasterProvider from "@/components/provider/Toaster";


const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Build 91 app ",
  description: "Generated by create next app",
  icons: {
    icon: "/favicon.ico", // <-- pas /public/
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ConvexAuthNextjsServerProvider>  
    <html lang="en" suppressHydrationWarning={true}>
      
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased `}
       >
        <NetworkStatus/>
        <ConvexClientProvider> <ThemeProvider
            attribute="class"
            defaultTheme="system"
            enableSystem
            disableTransitionOnChange
          >
            <ToasterProvider/>
            {children}
          </ThemeProvider></ConvexClientProvider>
        < Modals/>
      </body>
    </html>
    </ConvexAuthNextjsServerProvider>
  );
}
